# Generated by Django 3.2.15 on 2022-09-29 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220929_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinvoicedetails',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.hotelroomreservation'),
        ),
    ]
