# Generated by Django 3.2.15 on 2022-09-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reservationinvoicedetails_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hotelroom'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
